version: '3'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:alpine"
  sandbox:
    build: .
    volumes:
      - ./configs/docker.yml:/cb/config.yml
    env_file:
      - ./configs/docker.env
    environment:
      - ENVIRONMENT=development
    ports:
      - "5000:5000"
    links:
      - redis
      - postgres
