environment: development
loglevel: DEBUG
cbth_profile: default
connector_dirs:
  - /usr/share/cb/integrations
  - src/connectors
result_sinks:
  "null":
    kind: feed
    id: WurBK7L4Tm6SqJobP1lBUw
  yara:
    kind: feed
    id: WurBK7L4Tm6SqJobP1lBUw
  # yara:
  #   kind: watchlist
  #   id: some_watchlist_id
