cbth_profile: default
connector_dirs:
  - /opt/cb/integrations
feed_size: 50
binary_timeout: 600
result_sinks:
  "null":
    kind: feed
    id: WurBK7L4Tm6SqJobP1lBUw
  yara:
    kind: feed
    id: WurBK7L4Tm6SqJobP1lBUw
  # yara:
  #   kind: watchlist
  #   id: some_watchlist_id
  taxii:
    kind: feed
    id: 5BUoxlXSY2MitUEgFJHUA
