site: test.taxiistand.com
discovery_path: /read-only/services/discovery
collection_management_path: /read-only/services/collection-management
poll_path: /read-only/services/poll
use_https: True
ssl_verify: False
cert_file: 
key_file: 
default_score: 50
username: 
password: 
collections: '*'
start_date: 2019-01-01 00:00:00
minutes_to_advance: 1440
ca_cert: 
http_proxy_url:
https_proxy_url:
reports_limit: 10000

